# Temporary dockerfile for mysql and postgres

version: "3"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: knex_test
      MYSQL_USER: root
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: knex_test